// !!! This is a file automatically generated by hipify!!!
#include <Python.h>
#include <torch/script.h>

#ifdef WITH_CUDA
#include <hip/hip_runtime.h>
#endif

#ifdef _WIN32
#ifdef WITH_CUDA
PyMODINIT_FUNC PyInit__version_cuda(void) { return NULL; }
#else
PyMODINIT_FUNC PyInit__version_cpu(void) { return NULL; }
#endif
#endif

int64_t cuda_version() {
#ifdef WITH_CUDA
  return HIP_VERSION;
#else
  return -1;
#endif
}

static auto registry =
    torch::RegisterOperators().op("torch_sparse::cuda_version", &cuda_version);
